### ISSUE TITLE
"gtk3-mushrooms/src/gtk3.22.19: No such file or directory"

### ISSUE THREAD

**Issue by cimarronline** [lah7/gtk3-classic#1]
Great improvement for GTK3. One small issue, though. When I attempted to build from your PKGBUILD, it failed with the error "line 138: cd: /gtk3-mushrooms/src/gtk3.22.19: No such file or directory"

It's apparently the `cd "$srcdir/gtk-$pkgver"` (used three times). The GTK3 source cloned into a directory named simply "gtk+" rather than specifying the package version. A little editing got me past the error, but maybe the PKGBUILD could be corrected.

EDIT: Sorry, never mind. This was probably due to my using a different source (a later GTK3 commit that fixed a bug that was bugging me).

**Comment by TomaszGasior** [comment]
Thanks for your activity.

It is possible to get GTK source code by two ways.

- We can get source code from GIT repository. This way is used by ArchLinux packages in their PKGBUILDs. This way gives ability to add patches outside normal releases. For example after releasing current GTK version, some bugs were fixed in GIT repository. By one line (`git cherry-pick`) ArchLinux packager can apply part of next release to current release code. This way has small disadvantage — `makepkg` downloads all commits from GIT repository since 1997. It is very slooooow with my internet connection.
- To avoid this problem I use second way of getting GTK source code. It is possible to download prepared *.tar.xz and *.zip files from GitHub releases page and from GNOME file servers. This way is less flexible — it is impossible to apply patches from repository. But it is simpler and faster for me. I use it for me convenience. 

Because of this change name of created subdirectory is other than in original PKGBUILD.

**Comment by cimarronline** [comment]
Interesting, thanks. Yes, I did modify your PKGBUILD with some code from the latest Arch gtk3 PKGBUILD, including a cherry-pick command. It corrected a little bug in the earlier release.
