### ISSUE TITLE
Firefox 60 double titlebar buttons

### ISSUE THREAD

**Issue by cimarronline** [lah7/gtk3-classic#10]
In Firefox 60 (being released in about a week), there is a new option to remove the titlebar, basically switching it to CSD. If using gtk3-mushrooms, however, this results in double titlebar buttons:

![titlebars](https://user-images.githubusercontent.com/26089984/39580360-8aeeba10-4ed8-11e8-9a89-067d626847e2.png)

I use devilspie to remove the titlebar just from Firefox, and something like this may be the recommended solution for people who prefer the integrated titlebar in Firefox. This may not be an issue for most gtk3-mushrooms users. I just thought I'd bring it to your attention, in case there was some better solution.

**Comment by TomaszGasior** [comment]
gtk3-mushrooms forces Server Side Decoration even when application wants to use Client Side Decoration.

If you want to avoid double titlebar buttons you have to choose one following option.
* Don't use new feature in Firefox. Go to customizing screen and keep "Titlebar" option checked.
* Use client side decorations in Firefox. In this case you have to manually enable CSDs in gtk3-mushrooms. To achieve this you have to start Firefox with `GTK_CSD=0` or `GTK_CSD=1` environment variable (difference between `0` and `1` is described in [README.md](https://github.com/TomaszGasior/gtk3-mushrooms/blob/master/README.md)). For example start Firefox by `env GTK_CSD=0 firefox` command.

If you want to keep gtk3-mushrooms on your computer and disable CSDs for all apps except Firefox follow these steps.
1. Go to `/usr/share/applications/`.
2. Find `firefox.desktop` file and copy it. This file can be called `firefox.desktop` or just `Firefox`. (If you think about Developer Edition, search `firefox-developer-edition.desktop` or `Firefox Developer Edition` name.) Just copy this file.
3. Go to `~/.local/share/applications/`. Create this directory if it doesn't exist.
4. Paste copied file to this directory.
5. Open this file in text editor — gedit, mousepad, pluma, kwrite, nano, vim, sublime, just simple text editor
6. Find this line `Exec=/usr/lib/firefox/firefox %u` and change it to this: `Exec=env GTK_CSD=0 /usr/lib/firefox/firefox %u`. Important: `Exec` is repeated twice because activator contains "private window"  and "new window" additional actions, you may want to update it too.
7. Save file. Close Fx and reopen it by created activator (from apps menu). 
8. Go to customization screen and uncheck "titlebar" option.

Effect: all apps except Firefox have forced SSDs. Firefox has CSDs.
https://i.imgur.com/D566ZgP.png

**Comment by cimarronline** [comment]
Yes, that's a better solution, thanks.
