### ISSUE TITLE
Improper clearing of the background in tray icons

### ISSUE THREAD

**Issue by 9ary** [lah7/gtk3-classic#12]
Hi.
I've noticed for a while now that my tray icons have problems with clearing the background. I thought it was i3 or Mesa's fault, but I've managed to pin the issue down on the latest update to this package. I'll investigate more later, but I'm leaving this here for now.

**Comment by 9ary** [comment]
Actually I think I know exactly what the problem is, it's related to last time. I'll see what I can do.

**Comment by 9ary** [comment]
Yup, turns out it's [this](https://github.com/GNOME/gtk/commit/01d1bc3c75fd0eff5665f5b9c690c5e1e6c65f13). You might be missing an extra patch that makes tray icons `ParentRelative`, or they forgot to do it.

**Comment by TomaszGasior** [comment]
You are right. But I am not sure whether GTK authors created a special patch for tray icons case because… tray icons are deprecated and no one in GTK team is interested in supporting it. I try to find the solution if I find some time for it.

**Comment by 9ary** [comment]
Yeah I've looked around in their 3.23 branch and it doesn't seem like they've added a workaround for it. I'll try to come up with a patch today and I'll send you a PR to include it if you're fine with it.

**Comment by TomaszGasior** [comment]
Okay, thanks!

**Comment by 9ary** [comment]
It looks like this is enough in the most common case, maybe there are ways to break it, I'm not sure under which circumstances the `set_background` function gets called other than `tmp_unset/reset_bg`, but that shouldn't affect systray icons. It probably needs a check for parent depth as well, I'm not sure how many systray implementations actually support 32 bit color depth, if any.
```diff
--- gtk/deprecated/gtktrayicon-x11.c.orig
+++ gtk/deprecated/gtktrayicon-x11.c
@@ -967,6 +967,8 @@
     {
       /* Set a parent-relative background pixmap */
       gdk_window_set_background_pattern (window, NULL);
+      XSetWindowBackgroundPixmap (GDK_WINDOW_XDISPLAY (window),
+				  GDK_WINDOW_XID (window), ParentRelative);
     }
 G_GNUC_END_IGNORE_DEPRECATIONS
 
```

**Comment by 9ary** [comment]
I've been using the proposed hack for a while and it seems to work alright most of the time, but it does break once in a while. I think I'm going to take this upstream and see if they actually intend to fix this.
https://gitlab.gnome.org/GNOME/gtk/issues/1280

**Comment by TomaszGasior** [comment]
Thank you for your good job! 

If GTK authors won't apply your patch (maybe because gtktrayicon is deprecated) I will apply it in gtk3-mushrooms.

**Comment by 9ary** [comment]
I expect a more proper fix from them if they actually decide to fix it. If not, I can try to come up with a better solution myself, but I'm not sure how to approach it.

**Comment by TomaszGasior** [comment]
After an 8-hour fight between me and GTK codebase, I found it. Please look at the second branch: https://github.com/TomaszGasior/gtk3-mushrooms/commit/9851597ff365b3ff370bb8be2f2758d481f99f48
If you can, please test it in i3wm, awesome and other WMs you are using or you know. If it will be good, I will prepare a new release.
There is prebuilt package here: [gtk3-mushrooms-3.22.30-9-x86_64.pkg.tar.xz.zip](https://github.com/TomaszGasior/gtk3-mushrooms/files/2312543/gtk3-mushrooms-3.22.30-9-x86_64.pkg.tar.xz.zip)

My code is based on your pull request. It's still ugly and hackish but maybe more easy to maintain.  It seems to me there is no chance to see your or my code in upstream GTK, GTK authors have to find better solutions (ours are ugly) or maybe they just ignore it (because gtkstatusicon is deprecated).

**Comment by 9ary** [comment]
Deprecation is not a valid reason not to fix a regression. If it breaks existing applications, it should be fixed, until the feature is actually yanked.
I've left comments on your commit. I don't doubt it will work, but I like mine better, because it preserves the intended behavior and only touches tray icons.

**Comment by TomaszGasior** [comment]
I wanted to avoid patching "gdkinternals.h" but I understand your opinion. Maybe GTK authors will find better solution…

**Comment by oberon-manjaro** [comment]
I've been running the latest patch for a while now and somehow the fix seems less reliable than the previous one. Most of the time the tray looks ok, just sometimes I do get faulty backgrounds again and can correct those by "restarting-in-place" i3, so it is definitely better than without the patch - but not perfect I'm afraid.
Is there any additional information I can provide for you to further troubleshoot?

**Comment by 9ary** [comment]
Well with the patch I've proposed, I haven't seen broken backgrounds in a while now (which is expected since it tackles the problem directly). We know exactly what the issue is, see the GTK ticket for more info.

**Comment by TomaszGasior** [comment]
Okay. When GTK maintainers will release GTK 3.24 and this bug won't be fixed in upstream, I will append @Streetwalrus patch (it's better than mine) to gtk3-mushrooms. But I hope GTK people will find a better solution than hackish patching.

Currently, I am waiting for new GTK 3 release or fix from upstream.

@oberon-manjaro  switch back to patch from @Streetwalrus. It's here: https://raw.githubusercontent.com/Streetwalrus/gtk3-mushrooms/d1ba833faa76cc47b339d6a9e6fcc8b814fefe9d/fixes__gtktrayicon-background._patch

**Comment by TomaszGasior** [comment]
Also, I wonder whether this bug is visible in window managers other than i3 and Awesome (I checked Awesome too). Maybe there is something wrong with them? I have not any problems with XFCE's and MATE's window managers.

**Comment by 9ary** [comment]
This is a problem with systray implementations that use the xembed-based specification, but I'm pretty sure anything that uses GtkStatusIcon is affected independently of the WM.

**Comment by TomaszGasior** [comment]
I released gtk3-mushrooms 3.24.0-1 without any patch about this problem. I will try to look at this tomorrow.

**Comment by TomaszGasior** [comment]
Finally.

For now, it's fixed by https://github.com/TomaszGasior/gtk3-mushrooms/commit/c5f1b69b1d37a2723b043727965e65a1e7e42d01 and this patch: https://github.com/TomaszGasior/gtk3-mushrooms/blob/3.24.1-2/fixes__trayicon-parent-relative.patch

I hope the GTK team will find a better solution. If you see any issues with fix, please reopen.

**Comment by 9ary** [comment]
Looks reasonable to me, thanks.

**Comment by lbratch** [comment]
It looks like this may have been fixed upstream: https://gitlab.gnome.org/GNOME/gtk/commit/4c8fcd6a6f2adf9686296f8447895c0e2910075c

**Comment by TomaszGasior** [comment]
Thank you for information. I already saw this commit. It's great that GNOME people found time to fix it.
