### ISSUE TITLE
Suggestion: Icons in dropdown menus

### ISSUE THREAD

**Issue by Imerion** [lah7/gtk3-classic#20]
Hi!

This is a fantastic project that really makes GTK3 more useful, practical and efficient! I'm very happy you have created this. I have managed to hack in a few of these changes on my own in order to make things work as well as they once did, but many of these things I have not managed to fix without changing the code. So thanks!

Now for my issue: Would if be possible to bring back icons in drop-down menus in GTK3? They made it so much easier to quickly find the correct item, and I find dropdowns to be a very smart and efficient way of organising complex software with many functions.

**Comment by TomaszGasior** [comment]
This patch already restores icons in bult-in GTK content menus; https://github.com/TomaszGasior/gtk3-mushrooms/blob/master/appearance__buttons-menus-icons.patch
You can see the effect here: https://raw.githubusercontent.com/wiki/TomaszGasior/gtk3-mushrooms/screenshots/icons.png

It's impossible to restore icons in  applications menus because application itself is responsive to define icons on menus, no the toolkit.

**Comment by Imerion** [comment]
I see! Having them in the built-in content menus is great though, so thanks for that!
