### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by TomaszGasior** [lah7/gtk3-classic#30]
Hi, krumelmonster.  Are you going to maintain gtk3-mushrooms project? If you don't have time or just don't want to maintain it, it may be good idea to say it explicitly by making this project "archived" on the GitHub project settings.

**Comment by krumelmonster** [comment]
I really hope we could find someone else to maintain this project. I never managed to develop a worflow for at least moving the patches along with the progress of gtk3 releases

**Comment by TomaszGasior** [comment]
I think the best way to solve this problem is to abandon the whole project. Basically what I would like to suggest is:
- update README: tell people that this project is abandoned,
- archive this project on GitHub ("archive" buton in project settings),
- orphan package in the AUR.

If someone would like to continue the project then he can:
- fork your repository,
- take ownerhip of AUR package.

This way the situation will be more obvious for community, I think. Of couse, do what you want. :)

**Comment by krumelmonster** [comment]
I will archive the project later as this make issues and comments read only

**Comment by jonathonf** [comment]
I've been maintaining `gtk3-classic` on the AUR for a while and wonder whether it should just merge with `gtk3-mushrooms` as they do basically the same thing. I'm happy to take over the `-mushrooms` AUR package and then merge `-classic` into it (or vice versa).

@lah7 has also been in touch so there might be some movement on future maintenance too, but we're not sure whether his fork or mine should be the "upstream" given neither of us really understands the underlying patches (I can easily make patches apply, less so fix things broken by GTK updates).

**Comment by krumelmonster** [comment]
Sounds good, I think I can transfer the repository

**Comment by lah7** [comment]
@krumelmonster As mentioned above, I'd like to be "upstream" so the project has a central point for bug tracking and contributors as well as getting it up to date with @jonathonf's good efforts with the `gtk3-classic` AUR package. Even though I won't be writing any new patches, it's good to show the project is still alive.

When you get chance, please:
* Transfer this repository to @lah7
* Transfer `gtk3-mushrooms` on the AUR to @jonathonf.

Regarding the AUR packages, I personally quite like `gtk3-classic` naming over `gtk3-mushrooms`, since it would be ideal for one to replace the other.

**Comment by krumelmonster** [comment]
I transferred the AUR repo but I'm confused about who to transfer the git repository to. Can you, @lah7 and @jonathonf , come to a consensus on who I should transfer this git repository to?

**Comment by jonathonf** [comment]
> who I should transfer this git repository to?

Please transfer this repo to @lah7 . :+1:

**Comment by lah7** [comment]
Thanks :+1: Transfer complete.
