### ISSUE TITLE
Scroll down problem on some programs

### ISSUE THREAD

**Issue by geplus** [lah7/gtk3-classic#5]
Hi, 
I can't scroll down the pages in some programs that uses wxgtk and wxgtk3:
- Mediainfo-gui https://github.com/MediaArea/MediaInfo/issues/202#issuecomment-359245585

- guayadeque's lastfm's artist bio page

Can you verify if this is caused by gtk3-mushrooms and eventually fix that?

**Comment by TomaszGasior** [comment]
Hi, geplus. Thanks for activity.

There is no problem with mediainfo-gui of with GTK3-mushrooms. There is a bug in wxWidgets, which was fixed in upstream git repository, but new version of wxWidgets wasn't released yet.

GTK3 introduced feature called "overlay scrollbars". When it is enabled, scrollbars of scrolled box are not visible unless mouse is not over this box. When this feature is disabled, scrollbars are alvays visible. You can change it by `GTK_OVERLAY_SCROLLING` environment variable with value `1` (enabled) or `0` (disabled). Normally GTK3 has this feature enabled. GTK3-mushrooms disables this feature by default. Regardless of used GTK3 (vanilla or with my patches) you can enable or disable overlay scrollbars.

There is a bug in wxWidgets. If overlay scrollbars are enabled, everything works fine. If disabled, sometimes user can't scroll in HTML box. See this bug report: https://trac.wxwidgets.org/ticket/17915?cversion=0&cnum_hist=7. It is makred as fixed because fix was applied to master branch on git repository on August 2017. But the newest stable version of wxWidgets was released on May 2017 and have not this fix — maybe Arch Linux packager of wxWidgets should apply this patch?

https://github.com/wxWidgets/wxWidgets/commit/7626292fa4b1dbb5233ee8d9f924d8c56e150b1f.patch

Arch Linux bug report:
https://bugs.archlinux.org/task/57179

Currently as workaround you can fix it by this command in terminal:
`GTK_OVERLAY_SCROLLING=1 mediainfo-gui`

**Comment by TomaszGasior** [comment]
Problem fixed by Arch Linux package maintainer. You can download new version of `wxgtk3` package here:
https://www.archlinux.org/packages/extra/x86_64/wxgtk3/download/
or wait until it will be available in your repositories.
