### ISSUE TITLE
"Other locations"  removed : patch does not allow for access on network devices?

### ISSUE THREAD

**Issue by revast** [lah7/gtk3-classic#8]
I applied this patch, and now have no possibility to access network devices, even mounted ones...

**Comment by TomaszGasior** [comment]
GTK's file chooser has option called [`local-only`](https://developer.gnome.org/gtk3/stable/GtkFileChooser.html#GtkFileChooser--local-only), which can be set by application (not by user). Available values are TRUE or FALSE. If it is set to TRUE, network shares (mounted or not) and virtual file systems (like Trash) or other network resources (FTP for example) are not accessible from file chooser dialog. TRUE is default value, which means application author have to want to change this value to FALSE.
For example you can compare Mousepad (text editor for Xfce4) and Pluma (editor for MATE, fork of gedit with normal non-smartphone-stupid-like-interface). Mousepad don't allow to choose shares or files from trash (hmmm…) but Pluma allows to open file from trash or network share. Regardless of used GTK3 (original or `gtk3-mushrooms`).
Places sidebar of file chooser dialog always shows *mounted* network shares (if `local-only` is set to FALSE by app), unmounted are not shown. 

My patch disables "other places" button from places sidebar — I don't like it because thanks to this file chooser dialog looks more like small version of Nautilus. I don't use GNOME or Nautilus, I don't want it. I don't want to use two clicks instead one click to get access to unmounted disk partitions because GNOME developers like good appearance more than ergonomics. But without "other places" button you can't open  additional page which allows to mount network share.
Currently I don't have plans to remove this patch from my package. If I have to connect to FTP or mount network share, I am opening it in my file manager (Thunar or Caja) and then I have access to it in file chooser window.

-------

If you really want to use file chooser to mount network share and keep `gtk3-mushrooms` i have three solutions for you.

# Compile package without unwanted patch

```
git clone https://aur.archlinux.org/gtk3-mushrooms.git
cd gtk3-mushrooms
pluma PKGBUILD
makepkg
```
In third step open `PKGBUILD` with favourite editor, for example Pluma, and at the beginning of `__patch_gtk_code()` function add:
```
rm $srcdir/file-chooser__places-sidebar.patch
```

# Use bookmark

Open your file manager and show location field (probably Ctrl+L). Type `network://` and add this location to bookmarks — drag&drop to sidebar or use Bookmark->Add bookmark menu or something else.
Alternatively open `~/.config/gtk-3.0/bookmarks` and append `network:// Network` to the end.

Then when you open file chooser dialog, "Network" bookmark will be available from places sidebar (only if `local-only` is set to FALSE by app).

# Go to GVFS URL directly

Open file chooser dialog. Press `Ctrl+L` and type `network://`, press enter. If application changed `local-only` setting to FALSE, you'll see network shares. If no, nothing happens.

**Comment by TomaszGasior** [comment]
@revast I hope your problem will be solved by https://github.com/TomaszGasior/gtk3-mushrooms/commit/c5f1b69b1d37a2723b043727965e65a1e7e42d01. Now, places sidebar shows "Networks" button instead "Other locations".

**Comment by revast** [comment]
I'll give it a try
